ci: updates

diff --git a/build/package/alpine-builder/Dockerfile b/build/package/alpine-builder/Dockerfile
--- a/build/package/alpine-builder/Dockerfile
+++ b/build/package/alpine-builder/Dockerfile
@@ -6,7 +6,7 @@ FROM golang:${GOVERSION} as builder
 
 RUN apt-get update && apt-get upgrade -y ca-certificates && apt-get install -y bash && apt-get install -y unzip
 
-RUN curl -L -o gotestsum.tgz "https://github.com/gotestyourself/gotestsum/releases/download/v0.5.2/gotestsum_0.5.2_linux_amd64.tar.gz" && \
+RUN curl -L -o gotestsum.tgz "https://github.com/gotestyourself/gotestsum/releases/download/v1.6.4/gotestsum_1.6.4_linux_amd64.tar.gz" && \
     tar -C /usr/local/bin -xzf gotestsum.tgz && \
     rm gotestsum.tgz && \
     rm /usr/local/bin/LICENSE && \
@@ -25,7 +25,7 @@ COPY plugins ./plugins
 
 RUN --mount=type=cache,target=/go/pkg/mod \
     --mount=type=cache,target=/root/.cache/go-build \
-    gotestsum --format standard-verbose --junitfile /reports/junit.xml --raw-command -- go test -parallel 5 --json ./... || echo "failed"
+    gotestsum --format standard-verbose --junitfile ./reports/junit.xml --raw-command -- go test -parallel 5 --json ./... || echo "failed"
 
 RUN --mount=type=cache,target=/go/pkg/mod \
     --mount=type=cache,target=/root/.cache/go-build \
